[2018-09-21 11:12:21] INFO [run: run.py, 12] ================================== 测试开始 ==================================
[2018-09-21 11:12:21] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:12:21] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:12:21] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:12:21] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:12:21] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:12:21] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:12:21] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:12:21] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:12:21] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:12:21] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:12:21] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:12:21] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:12:21] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:12:21] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:12:22] DEBUG [query_db: db.py, 27] ((96, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:12:22] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:12:23] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:12:23] INFO [run: run.py, 20] ================================== 测试结束 ==================================
[2018-09-21 11:13:07] INFO [run: run.py, 12] ================================== 测试开始 ==================================
[2018-09-21 11:13:07] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:13:07] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:13:07] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:13:07] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:13:07] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:13:07] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:13:07] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:13:07] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:13:07] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:13:07] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:13:07] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:13:07] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:13:07] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:13:07] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:13:07] DEBUG [query_db: db.py, 27] ((97, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:13:07] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:13:08] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:13:08] INFO [run: run.py, 20] ================================== 测试结束 ==================================
[2018-09-21 11:14:31] INFO [run: run.py, 12] ================================== 测试开始 ==================================
[2018-09-21 11:14:31] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:14:31] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:14:31] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:14:31] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:14:31] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:14:31] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:14:31] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:14:31] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:14:31] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:14:31] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:14:31] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:14:31] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:14:31] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:14:31] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:14:31] DEBUG [query_db: db.py, 27] ((98, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:14:31] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:14:32] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:14:32] INFO [run: run.py, 21] ================================== 测试结束 ==================================
[2018-09-21 11:15:16] INFO [run: run.py, 12] ================================== 测试开始 ==================================
[2018-09-21 11:15:16] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:15:16] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:15:16] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:15:16] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:15:16] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:15:16] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:15:16] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:15:16] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:15:16] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:15:16] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:15:16] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:15:16] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:15:16] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:15:16] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:15:16] DEBUG [query_db: db.py, 27] ((99, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:15:16] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:15:17] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:15:17] INFO [run: run.py, 21] ================================== 测试结束 ==================================
[2018-09-21 11:28:05] INFO [run: run.py, 13] ================================== 测试开始 ==================================
[2018-09-21 11:28:05] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:28:05] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:28:05] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:28:05] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:28:05] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:28:05] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:28:05] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:28:05] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:28:05] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:28:05] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:28:05] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:28:05] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:28:05] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:28:05] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:28:05] DEBUG [query_db: db.py, 27] ((100, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:28:05] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:28:44] INFO [run: run.py, 13] ================================== 测试开始 ==================================
[2018-09-21 11:28:44] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:28:44] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:28:44] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:28:44] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:28:44] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:28:44] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:28:44] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:28:44] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:28:45] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:28:45] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:28:45] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:28:45] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:28:45] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:28:45] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:28:45] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:28:45] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:28:45] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:28:45] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:28:45] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:28:45] DEBUG [query_db: db.py, 27] ((101, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:28:45] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:28:46] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:28:46] INFO [run: run.py, 23] ================================== 测试结束 ==================================
[2018-09-21 11:31:24] INFO [run: run.py, 13] ================================== 测试开始 ==================================
[2018-09-21 11:31:24] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:31:26] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:31:26] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:31:26] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:31:26] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:31:26] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:31:26] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:31:26] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:31:26] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:31:26] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:31:26] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:31:26] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:31:26] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:31:26] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:31:26] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:31:27] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:31:27] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:31:27] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:31:27] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:31:27] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:31:27] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:31:27] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:31:27] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:31:27] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:31:27] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:31:27] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:31:27] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:31:27] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:31:27] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:31:27] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:31:27] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:31:27] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:31:27] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:31:27] DEBUG [query_db: db.py, 27] ((102, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:31:27] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:31:28] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:31:28] INFO [run: run.py, 23] ================================== 测试结束 ==================================
[2018-09-21 11:32:38] INFO [run: run.py, 13] ================================== 测试开始 ==================================
[2018-09-21 11:32:38] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:32:38] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:32:38] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:32:38] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:32:38] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:32:38] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:32:38] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:32:38] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:32:38] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:32:38] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:32:38] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:32:38] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:32:38] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:32:38] DEBUG [query_db: db.py, 27] ((103, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:32:38] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:32:38] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:32:38] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:32:38] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:32:39] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:32:39] INFO [run: run.py, 23] ================================== 测试结束 ==================================
[2018-09-21 11:38:00] INFO [run: run.py, 13] ================================== 测试开始 ==================================
[2018-09-21 11:38:00] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:38:00] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:38:00] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:38:00] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:38:00] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:38:00] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:38:00] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:38:00] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:38:00] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:38:00] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:38:03] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:38:03] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:38:03] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:38:03] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:38:03] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:38:03] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:38:03] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:38:03] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:38:03] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:38:03] DEBUG [query_db: db.py, 27] ((104, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:38:03] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:38:04] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:38:04] INFO [run: run.py, 23] ================================== 测试结束 ==================================
[2018-09-21 11:38:46] INFO [run: run.py, 13] ================================== 测试开始 ==================================
[2018-09-21 11:38:46] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:38:46] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:38:46] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:38:46] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:38:46] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:38:46] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:38:46] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:38:46] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:38:46] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:38:46] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:38:46] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:38:46] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:38:46] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:38:46] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:38:46] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:38:50] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:38:50] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:38:50] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:38:50] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:38:50] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:38:50] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:38:50] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:38:50] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:38:50] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:38:50] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:38:50] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:38:50] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:38:50] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:38:50] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:38:50] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:38:50] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:38:50] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:38:50] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:38:50] DEBUG [query_db: db.py, 27] ((105, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:38:50] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:38:52] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:38:52] INFO [run: run.py, 23] ================================== 测试结束 ==================================
[2018-09-21 11:39:50] INFO [run: run.py, 13] ================================== 测试开始 ==================================
[2018-09-21 11:39:50] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:39:50] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:39:50] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:39:50] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:39:50] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:39:50] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:39:50] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:39:50] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:39:50] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:39:50] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:39:50] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:39:50] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:39:50] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:39:50] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:39:50] DEBUG [query_db: db.py, 27] ((106, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:39:50] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:39:51] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:39:51] INFO [run: run.py, 24] ================================== 测试结束 ==================================
[2018-09-21 11:40:01] INFO [run: run.py, 13] ================================== 测试开始 ==================================
[2018-09-21 11:40:01] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:40:02] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:40:02] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:40:02] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:40:02] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:40:02] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:40:02] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:40:02] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:40:02] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:40:02] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:40:02] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:40:02] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:40:02] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:40:02] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:40:02] DEBUG [query_db: db.py, 27] ((107, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:40:02] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:40:03] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:40:03] INFO [run: run.py, 24] ================================== 测试结束 ==================================
[2018-09-21 11:40:03] INFO [run: run.py, 13] ================================== 测试开始 ==================================
[2018-09-21 11:40:03] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:40:03] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:40:03] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:40:03] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:40:03] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:40:03] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:40:03] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:40:04] INFO [send_email: send_email.py, 27] 邮件发送完成！
[2018-09-21 11:40:04] INFO [run: run.py, 24] ================================== 测试结束 ==================================
[2018-09-21 11:47:21] INFO [run: run.py, 14] ================================== 测试开始 ==================================
[2018-09-21 11:47:21] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:47:21] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:47:21] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:47:21] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:47:21] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:47:21] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:47:21] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:47:21] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:47:21] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:47:21] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:47:21] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:47:21] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:47:22] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:47:22] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:47:22] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:47:22] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:47:22] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:47:22] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:47:22] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:47:22] DEBUG [query_db: db.py, 27] ((108, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:47:22] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:47:22] INFO [run: run.py, 25] ================================== 测试结束 ==================================
[2018-09-21 11:47:22] INFO [run: run.py, 14] ================================== 测试开始 ==================================
[2018-09-21 11:47:22] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:47:22] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:47:22] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:47:22] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:47:22] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:47:22] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:47:22] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:47:22] INFO [run: run.py, 25] ================================== 测试结束 ==================================
[2018-09-21 11:50:32] INFO [run: run.py, 15] ================================== 测试开始 ==================================
[2018-09-21 11:50:32] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:50:32] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 11:50:32] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:50:32] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:50:32] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2018-09-21 11:50:32] DEBUG [query_db: db.py, 27] ((3, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:50:32] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:50:32] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三", "password": "123456"}
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100001', 'msg': '失败，用户已存在', 'data': {'name': '张三', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 11:50:32] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:50:32] DEBUG [query_db: db.py, 27] ()
[2018-09-21 11:50:32] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:50:32] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰", "password": "123456"}
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 13] 期望结果：{'code': '100000', 'msg': '成功', 'data': {'name': '范冰冰', 'password': 'e10adc3949ba59abbe56e057f20f883e'}}
[2018-09-21 11:50:32] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 11:50:32] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2018-09-21 11:50:33] DEBUG [query_db: db.py, 27] ((109, '范冰冰', 'e10adc3949ba59abbe56e057f20f883e'),)
[2018-09-21 11:50:33] DEBUG [change_db: db.py, 35] delete from user where name='范冰冰'
[2018-09-21 11:50:33] INFO [run: run.py, 26] ================================== 测试结束 ==================================
[2018-09-21 11:50:33] INFO [run: run.py, 15] ================================== 测试开始 ==================================
[2018-09-21 11:50:33] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 11:50:33] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 11:50:33] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 11:50:33] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 11:50:33] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 11:50:33] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:50:33] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 11:50:33] INFO [run: run.py, 26] ================================== 测试结束 ==================================
[2018-09-21 12:15:43] INFO [run: run.py, 15] ================================== 测试开始 ==================================
[2018-09-21 12:15:43] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 12:15:43] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 12:15:43] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 12:15:43] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 12:15:43] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 12:15:43] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 12:15:43] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 12:15:43] INFO [run: run.py, 26] ================================== 测试结束 ==================================
[2018-09-21 12:31:31] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 12:31:31] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 12:31:31] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 12:31:31] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 12:31:31] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 12:31:31] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 12:31:31] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:15:52] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 14:15:52] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 14:15:52] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 14:15:52] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 14:15:52] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 14:15:52] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:15:52] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:17:51] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2018-09-21 14:17:51] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2018-09-21 14:17:51] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 14:17:51] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 14:17:51] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 14:17:51] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:17:51] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:29:49] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 14:29:49] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 14:29:49] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 14:29:49] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:29:49] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:33:44] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 14:33:44] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 14:33:44] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 14:33:44] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:33:44] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:36:34] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 14:36:34] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 14:36:34] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 14:36:34] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 14:36:34] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 14:36:34] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 14:36:34] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 14:36:34] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 14:36:34] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:36:34] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 14:41:12] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 14:41:12] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 14:41:12] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 14:41:12] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 14:41:12] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 15:56:33] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 15:56:33] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 15:56:33] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 15:56:33] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 15:56:33] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 15:56:33] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 15:56:33] INFO [run: run.py, 74] ================================== 测试结束 ==================================
[2018-09-21 17:06:32] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:06:32] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:06:32] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:06:32] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:06:32] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:06:32] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:06:32] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:06:32] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:06:32] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:06:32] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:07:04] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:07:04] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:07:04] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:07:04] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:07:04] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:07:04] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:07:04] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:07:04] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:07:04] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:07:04] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:07:22] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:07:22] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:07:22] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:07:22] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:07:22] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:07:22] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:07:22] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:07:22] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:07:22] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:07:22] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:08:03] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:08:03] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:08:03] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:08:03] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:08:03] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:08:03] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:08:03] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:08:03] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:08:03] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:08:03] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:08:24] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:08:24] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:08:24] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:08:24] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:08:24] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:08:25] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:08:25] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:08:25] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:08:25] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:08:25] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:08:43] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:08:43] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:08:43] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:08:43] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:08:43] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:08:48] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:08:48] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:08:48] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:08:48] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:08:48] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:08:48] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:08:48] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:08:48] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:08:48] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:08:48] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:09:21] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:09:21] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:09:21] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:09:21] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:09:21] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:09:21] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:09:21] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:09:21] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:09:21] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:09:21] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:09:52] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:09:52] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:09:52] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:09:52] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:09:52] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:09:52] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:09:52] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:09:52] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:09:52] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:09:52] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:10:48] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:10:48] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:10:48] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:10:48] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:10:48] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:10:51] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:10:51] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:10:51] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:10:51] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:10:51] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:11:00] INFO [run: run.py, 62] ================================== 测试开始 ==================================
[2018-09-21 17:11:01] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:11:01] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:11:01] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:11:01] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:11:01] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:11:01] INFO [run: run.py, 72] ================================== 测试结束 ==================================
[2018-09-21 17:22:09] ERROR [get_test_data: read_excel.py, 23] 用例数据不存在
[2018-09-21 17:23:29] ERROR [get_test_data: read_excel.py, 23] 用例数据不存在
[2018-09-21 17:24:18] ERROR [get_test_data: read_excel.py, 23] 用例数据不存在
[2018-09-21 17:24:27] ERROR [get_test_data: read_excel.py, 23] 用例数据不存在
[2018-09-21 17:26:17] ERROR [get_test_data: read_excel.py, 23] 用例数据不存在
[2018-09-21 17:29:47] ERROR [get_test_data: read_excel.py, 23] 用例数据不存在
[2018-09-21 17:30:49] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:30:49] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:30:49] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:30:49] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:30:49] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:30:49] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:30:49] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:30:49] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:30:49] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:30:49] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:32:30] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 17:32:30] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 17:32:30] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:32:30] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100001", "data": {"name": "\u5f20\u4e09", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}
[2018-09-21 17:32:30] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 17:32:30] ERROR [get_test_data: read_excel.py, 23] 用例数据不存在
[2018-09-21 17:34:04] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 17:34:04] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 17:34:04] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:34:04] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100001", "data": {"name": "\u5f20\u4e09", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}
[2018-09-21 17:34:04] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 17:34:04] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 17:34:04] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 17:34:04] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰","password":"123456"}
[2018-09-21 17:34:04] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100000", "data": {"name": "\u8303\u51b0\u51b0", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u6210\u529f"}
[2018-09-21 17:34:04] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 17:34:49] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 17:34:49] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 17:34:49] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:34:49] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100001", "data": {"name": "\u5f20\u4e09", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}
[2018-09-21 17:34:49] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 17:34:49] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 17:34:49] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 17:34:49] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰","password":"123456"}
[2018-09-21 17:34:49] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100000", "data": {"name": "\u8303\u51b0\u51b0", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u6210\u529f"}
[2018-09-21 17:34:49] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 17:44:43] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:44:43] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:44:43] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:44:43] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:44:43] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:44:43] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:44:43] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:44:43] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:44:43] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:44:43] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:47:06] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 17:47:06] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:47:06] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 17:47:06] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 17:47:06] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 17:47:06] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 17:47:06] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 17:47:06] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 17:47:06] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 17:47:06] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 18:06:30] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 18:06:30] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 18:06:30] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 18:06:30] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 18:06:30] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 18:06:30] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 18:06:30] INFO [run: run.py, 73] ================================== 测试结束 ==================================
[2018-09-21 18:06:35] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 18:06:35] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 18:06:35] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 18:06:35] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 18:06:35] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 18:06:35] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 18:06:35] INFO [run: run.py, 73] ================================== 测试结束 ==================================
[2018-09-21 18:06:53] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 18:06:53] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 18:06:53] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 18:06:53] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 18:06:53] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 18:06:53] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 18:06:53] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 18:06:53] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 18:06:53] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰","password":"123456"}
[2018-09-21 18:06:53] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100000", "data": {"name": "\u8303\u51b0\u51b0", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u6210\u529f"}
[2018-09-21 18:06:53] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 18:06:53] INFO [run: run.py, 73] ================================== 测试结束 ==================================
[2018-09-21 18:16:37] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 18:16:37] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 18:16:37] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 18:16:37] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 18:16:37] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 18:16:37] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 18:16:37] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 18:16:37] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 18:16:37] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰","password":"123456"}
[2018-09-21 18:16:37] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100000", "data": {"name": "\u8303\u51b0\u51b0", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u6210\u529f"}
[2018-09-21 18:16:37] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 18:16:37] INFO [run: run.py, 73] ================================== 测试结束 ==================================
[2018-09-21 18:16:49] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 18:16:56] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 18:16:56] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 18:16:56] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 18:16:56] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 18:16:56] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 18:16:56] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 18:16:56] INFO [run: run.py, 73] ================================== 测试结束 ==================================
[2018-09-21 19:44:45] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 19:44:45] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 19:44:45] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 19:44:45] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 19:44:45] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 19:44:45] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 19:44:45] INFO [run: run.py, 73] ================================== 测试结束 ==================================
[2018-09-21 19:45:01] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 19:45:01] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 19:45:01] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 19:45:01] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 19:45:01] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 19:45:01] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 19:45:02] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 19:45:02] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 19:45:02] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰","password":"123456"}
[2018-09-21 19:45:02] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100000", "data": {"name": "\u8303\u51b0\u51b0", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u6210\u529f"}
[2018-09-21 19:45:02] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 19:45:02] INFO [run: run.py, 73] ================================== 测试结束 ==================================
[2018-09-21 19:45:15] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 19:45:15] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 19:45:15] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 19:45:15] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 19:45:15] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 19:45:15] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 19:45:15] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 19:45:15] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 19:45:15] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰","password":"123456"}
[2018-09-21 19:45:15] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100000", "data": {"name": "\u8303\u51b0\u51b0", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u6210\u529f"}
[2018-09-21 19:45:15] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 19:45:15] INFO [run: run.py, 73] ================================== 测试结束 ==================================
[2018-09-21 19:45:31] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 19:45:42] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 19:45:42] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 19:45:42] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 19:45:42] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 19:45:42] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 19:45:42] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 19:45:42] INFO [run: run.py, 73] ================================== 测试结束 ==================================
[2018-09-21 19:45:53] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100001", "data": {"name": "\u5f20\u4e09", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰","password":"123456"}
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100000", "data": {"name": "\u8303\u51b0\u51b0", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u6210\u529f"}
[2018-09-21 19:45:53] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2018-09-21 19:45:53] INFO [run: run.py, 73] ================================== 测试结束 ==================================
